2018-09-11T19:37:33.973Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '12345' as the object already exists)
    at /Users/treallison/Documents/Wake Tech Courses/CSC289/ZeroToBlockchain/Chapter04/node_modules/composer-connector-hlfv1/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-09-11T19:37:33.974Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '12345' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '12345' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/Users/treallison/Documents/Wake Tech Courses/CSC289/ZeroToBlockchain/Chapter04/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
